name: Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

# Grant the minimum permissions required for uploading coverage and commenting on PRs.
# If you prefer to use a PAT for commenting, set it in a secret and change the action inputs.
permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar tests
      run: npm run test:run

    - name: Ejecutar tests con cobertura
      run: npm run test:coverage

    - name: Subir cobertura a Codecov
      uses: codecov/codecov-action@v3
      if: ${{ success() && secrets.CODECOV_TOKEN }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info

    - name: Subir cobertura local (fallback)
      if: ${{ success() && !secrets.CODECOV_TOKEN }}
      run: |
        echo "No CODECOV_TOKEN found — keeping coverage artifacts in workflow run."

    - name: Comentar resultados en PR
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        message: |
          ## Resultados de Tests

          Todos los tests pasaron exitosamente

          Ver detalles en la pestaña "Actions" arriba.